name: Bot Hoy No Circula

on:
  # 1. AUTO-TEST AL GUARDAR CAMBIOS
  push:
    branches:
      - main
      
  # 2. BOTÓN MANUAL (Pruebas)
  workflow_dispatch:

  # 3. HORARIOS ESTRATÉGICOS (UTC)
  schedule:
    # Mañana: 6:05 AM CDMX (~12:05 UTC) -> Para saber qué auto se queda hoy.
    - cron: '5 12 * * *'
    # Noche: 8:05 PM CDMX (~02:05 UTC) -> Para saber qué auto descansa mañana.
    - cron: '5 2 * * *'

jobs:
  vigilancia_ambiental:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        # Agregamos requests y librerías de scraping
        run: pip install requests feedparser pytz ntscraper

      - name: Ejecutar Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
