name: Bot Hoy No Circula

on:
  workflow_dispatch: # Botón manual
  schedule:
    # Ejecución 1: 6:05 AM hora CDMX (12:05 UTC)
    - cron: '5 12 * * *'
    # Ejecución 2: 8:05 PM hora CDMX (02:05 UTC)
    - cron: '5 2 * * *'

jobs:
  vigilancia_ambiental:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        # ntscraper para Twitter, feedparser para noticias
        run: pip install requests feedparser pytz ntscraper

      - name: Ejecutar Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
